[versions]
gradle-starter = "0.60.1"
gradle-doctor = "0.8.1"
maven-junit = "5.9.3"
maven-assertj = "3.24.2"
maven-ktlint = "0.48.2"
maven-commons = "2.13.0"

[libraries]
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "maven-junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "maven-junit" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "maven-assertj" }
commons-io = { module = "commons-io:commons-io", version.ref = "maven-commons" }

[plugins]
starter-config = { id = "com.starter.config", version.ref = "gradle-starter" }
starter-versioning = { id = "com.starter.versioning", version.ref = "gradle-starter" }
starter-library-kotlin = { id = "com.starter.library.kotlin", version.ref = "gradle-starter" }
osacky-doctor = { id = "com.osacky.doctor", version.ref = "gradle-doctor" }
