name: Build project

on:
  pull_request:
  schedule:
    - cron: '0 3 * * 1,4'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Write Gradle build properties to `~/.gradle/gradle.properties`
        run: |
          mkdir -p ~/.gradle
          printf "org.gradle.jvmargs=-Xmx3G -XX:+UseParallelGC\n" >> ~/.gradle/gradle.properties
        shell: bash

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: |
            8
            11
            17
            20

      - uses: gradle/gradle-build-action@v2

      - uses: gradle/wrapper-validation-action@v1

      - run: ./gradlew projectCodestyle --scan

      - run: ./gradlew check --scan

      - run: ./gradlew projectCoverage --scan
